### ISSUE TITLE
NAB AL Tools?

### ISSUE THREAD

**Issue by jwikman** [waldo1001/ALExtensionPack#10]
Hi Waldo,

Have you tested out my little VSCode extension [NAB AL Tools](https://marketplace.visualstudio.com/items?itemName=nabsolutions.nab-al-tools)?

It contains a lot of Xliff features and some other goodies. Always open for feedback ;-)

Cheers,
Johannes

**Comment by waldo1001** [comment]
Wow - I had no idea 😳.  And already so many installs!

I'll put it on the list!  I want to look at it first, but that'll happen next month (well, next week ;-)) - too busy now.  Please remind me if it's not online in April ;-)

**Comment by jwikman** [comment]
It's been on the marketplace for a couple of years as a public preview, but just released the v1.0 version...

No hurry about this, I know this is a busy time of the year! 😁

**Comment by waldo1001** [comment]
Damn, I feel bad about this.. .

**Comment by jwikman** [comment]
No worries 😀

**Comment by jwikman** [comment]
Hi @waldo1001, remember me? 😜

I'm perfectly fine if you do not want this in your package, but I wish at least that it would be on purpose and not caused by lack time. ;-)

**Comment by waldo1001** [comment]
Well - it's absolutely not onpurpose to have a lack of time .. or a bad memory .. ;-).  

Here you go: 
https://github.com/waldo1001/ALExtensionPack/commit/c20e8655a3e874fbe7e8cb97cd2463175eba4b1e

**Comment by jwikman** [comment]
I hope you'll like it! :)
