### ISSUE TITLE
Remove Bracket Pair Colorizer 2

### ISSUE THREAD

**Issue by mrabus** [waldo1001/ALExtensionPack#13]
As the feature itself is implemented in VS Code natively, the maintainer will discontinue to support the extension. So, I argue it should be removed from the extension pack.

**Comment by waldo1001** [comment]
You are right - thanks.  And thanks for he PR!

**Comment by mrabus** [comment]
I'm benefiting from your Extension Pack, so thank you. 

Case closed 🙂
