### ISSUE TITLE
[Suggestion] Bracket Select

### ISSUE THREAD

**Issue by fvet** [waldo1001/ALExtensionPack#16]
A pity no one mentioned this in the 'Get productive in VS Code' sessions at BC Techdays, but this one's a nice one too in my opinion.

We use it a **lot** to select everything between **brackets, single quotes, quotes, ...**

Very useful to select e.g. the entire text between the supported delimiters via **Alt+A** (e.g. to get a field name that has spaces (with/without quotes), to get the full caption, content of a label, ...

@waldo1001 Worth testing and maybe a candidate for the ALExtensionPack ?

https://marketplace.visualstudio.com/items?itemName=chunsen.bracket-select

![Items](https://user-images.githubusercontent.com/25268332/191326384-16e37f0e-9c4b-457f-86ba-4ec8f0fe872d.gif)

**Comment by waldo1001** [comment]
hm - that's pretty awesome!
Going right in!  thanks!
