### ISSUE TITLE
Record is defined as temporary always.

### ISSUE THREAD

**Issue by ashikivor** [waldo1001/ALExtensionPack#2]
Hi,

The "AL Variable Helper" does a great job for the developers. 

But always the "Record" variable is temporary by default. 

I suppose the usage of the Record variable is more when compared to the temporary variable. 

Can we modify the snippet so that it does not define temporary by default?

**Comment by waldo1001** [comment]
No, you can't.

but this is the repo of the AL Variable Helper:
https://github.com/RasmusTidselbak/al-var-helper

you can log an issue there.
