### ISSUE TITLE
[Suggestion] Polacode

### ISSUE THREAD

**Issue by JeremyVyska** [waldo1001/ALExtensionPack#9]
Really useful for code screenshotting in a clean and tidy fashion for blogging, tweeting, and presentation use.

https://marketplace.visualstudio.com/items?itemName=jeff-hykin.polacode-2019

**Comment by waldo1001** [comment]
I looked into it, but as it's not really an AL-Language helper .. I'm not going to add it.

Also, there are a few things that could be improved:
- it always saves an image.  Would be awesome to "just" copy it to clipboard
- it creates too much black space on the right.. .

I do appreciate you take the time to add new ideas.  Keep it comin' ;-)
